# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9e009490ff76da7aebec0ff1689f10e59bf4d6fe2af3dbd29579afd39dbba8b684bfe4ec983b59a8dbed2f440986d089fe3c435349440d8475f87d5c61f2e3c

test:
  secret_key_base: e33d6ab71b8e44c60eae6fd234e2118a9d0bfff26e90509c229455dfcc3362950669b5dd10920b5efab9ca67e0c864121c0f128adbbf5ac65a09ce37b456b2ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
